import { scanFiles } from "./scanner.js";
import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";

/**
 * Generate .github/workflows/nlang.yml based on discovered files.
 * @param {string} rootDir
 */
export async function initWorkflow(rootDir) {
  console.log(`\n🔍 Scanning ${rootDir} for executable files...\n`);

  const files = await scanFiles(rootDir);
  console.log(`📂 Found ${files.length} executable file(s)`);

  // Collect cron schedules
  /** @type {Map<string, string[]>} - cron expression -> file paths */
  const cronMap = new Map();

  for (const file of files) {
    if (file.cron) {
      const existing = cronMap.get(file.cron) || [];
      existing.push(file.relativePath);
      cronMap.set(file.cron, existing);
    }
  }

  console.log(`⏰ Found ${cronMap.size} cron schedule(s)`);
  for (const [cron, paths] of cronMap) {
    console.log(`  ${cron}: ${paths.join(", ")}`);
  }

  // Generate the workflow
  const workflow = generateWorkflow(cronMap, files);

  // Write it
  const workflowDir = join(rootDir, ".github", "workflows");
  await mkdir(workflowDir, { recursive: true });
  const workflowPath = join(workflowDir, "nlang.yml");
  await writeFile(workflowPath, workflow);

  console.log(`\n✅ Generated ${workflowPath}\n`);
  console.log(`Next steps:`);
  console.log(
    `  1. Set OPENAI_API_KEY (or LLM_API_KEY) in your repo's Settings → Secrets`
  );
  console.log(`  2. Commit and push the workflow file`);
  console.log(
    `  3. Your files will be built on push and on the configured schedules\n`
  );
}

/**
 * Generate the YAML workflow content.
 * @param {Map<string, string[]>} cronMap
 * @param {import('./scanner.js').ExecutableFile[]} files
 * @returns {string}
 */
function generateWorkflow(cronMap, files) {
  // Build schedule entries
  const schedules = [];
  const cronEntries = [...cronMap.entries()];

  for (const [cron] of cronEntries) {
    schedules.push(`    - cron: '${cron}'`);
  }

  const hasSchedules = schedules.length > 0;
  const hasMdFiles = files.some((f) => f.executorExtension === ".md");
  const hasTsFiles = files.some((f) => f.executorExtension === ".ts");

  // Build the dispatch file mapping for cron triggers
  // We use workflow_dispatch inputs to allow targeted builds
  // For cron, we determine which files to build based on the schedule
  const cronDispatchLogic = cronEntries
    .map(([cron, paths], i) => {
      const condition = `elif [ "\${{ github.event.schedule }}" = "${cron}" ]; then`;
      // Build each file individually via --file flag
      const buildCmds = paths
        .map((p) => `            npx nlang build --file "${p}"`)
        .join("\n");
      return `          ${condition}\n${buildCmds}`;
    })
    .join("\n");

  const yaml = `# Generated by nlang - Executable Extensions
# https://github.com/nicely-defined/nlang
#
# This workflow builds double-extension files:
# - .xyz.md files are sent to an LLM API
# - .xyz.js/.ts files are executed in Node.js
# Output is written to the dist/ directory.

name: nlang build

on:
  push:
    branches: [main, master]
    paths-ignore:
      - 'dist/**'
      - '.nlang-cache/**'
${hasSchedules ? `  schedule:\n${schedules.join("\n")}` : ""}
  workflow_dispatch:
    inputs:
      file:
        description: 'Specific file to build (optional)'
        required: false
        type: string

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install nlang
        run: npm install -g nlang

${hasTsFiles ? `      - name: Install tsx (for TypeScript support)\n        run: npm install -g tsx\n` : ""}
      - name: Restore cache
        uses: actions/cache@v4
        with:
          path: .nlang-cache
          key: nlang-cache-\${{ github.sha }}
          restore-keys: |
            nlang-cache-

      - name: Build
        env:
          OPENAI_API_KEY: \${{ secrets.OPENAI_API_KEY }}
          LLM_API_KEY: \${{ secrets.LLM_API_KEY }}
        run: |
          if [ -n "\${{ github.event.inputs.file }}" ]; then
            npx nlang build --file "\${{ github.event.inputs.file }}"
${cronDispatchLogic ? `${cronDispatchLogic}\n          else\n            npx nlang build\n          fi` : "          else\n            npx nlang build\n          fi"}

      - name: Commit and push output
        run: |
          git config user.name "nlang[bot]"
          git config user.email "nlang[bot]@users.noreply.github.com"
          git add dist/ .nlang-cache/
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "nlang: build output [skip ci]"
            git push
          fi
`;

  return yaml;
}
